### ISSUE TITLE
Provide 32-bit release

### ISSUE THREAD

**Issue by wertercatt** [wesleyd1124/WLUS#11]
Without 32-bit support, users on 32-bit versions of windows are forced to use LUNI.

**Comment by ghost** [comment]
I'll try to get this out soon but I'm currently swamped. If you have 32-bit you can still run it through Python.

**Comment by ghost** [comment]
I'm honestly curious whether anyone actually need this - pretty sure 64 bit processors have been standard in consumer machines for the greater part of the last 10 years

**Comment by ghost** [comment]
This issue is no longer relevant in the rewrite. The old version will not be receiving support.
