### ISSUE TITLE
Here is an issue I am facing.

### ISSUE THREAD

**Issue by MajickTek** [wesleyd1124/WLUS#12]
Everything works. Every map loads fine, every command works, I can spawn anything.

However:

Nomatter which ports I change in the config I cannot seem to get it working over LAN, even on the same PC. I can correctly get the server to launch on my public IP, but the client refuses to connect.

I am using the release build if that helps. I realise a build from source could improve things greatly.

**Comment by BlakeTheGreat** [comment]
Open the boot.cfg in the LEGO Universe Client folder and change AUTHSERVERIP to read 'AUTHSERVERIP=0:localhost,' (this may already be the case depending on the client)

**Comment by MajickTek** [comment]
I don't think you understand the issue. It WORKS FINE on my localhost. but i cannot change the IP IN THE SERVER CONFIG and get it to work.

**Comment by BlakeTheGreat** [comment]
So you've gone to the config file and changed `redirect_address="127.0.0.1"` to `redirect_address="<your_ip>"` and put that same ip in your client and it would not connect?

**Comment by MajickTek** [comment]
yeah

**Comment by ghost** [comment]
Hey sorry about not seeing this issue sooner, I've been very busy. Make sure the bind address is 0.0.0.0 and the redirect address is your IP. Other than that the only other explanation I can think of is that you might have a firewall or some other software on your computer blocking incoming connections.

**Comment by MajickTek** [comment]
ok thanks, will try.

**Comment by ghost** [comment]
This issue is no longer relevant in the rewrite. The old version will not be receiving support.
