### ISSUE TITLE
What is not working?

### ISSUE THREAD

**Issue by moliata** [wesleyd1124/WLUS#13]
Hello,
I know you are probably not working on WLUS anymore, but I am interested, what is not working compared to the original LU.
Best regards,
Ben.

**Comment by ghost** [comment]
Well so far the server can load worlds and place objects in their correct locations with the correct config. Equipment and skills can be used for the most part. Missions don’t work at all, as well as all mini games. The server is badly structured and needs a rewrite/restructuring very much

**Comment by moliata** [comment]
@wesleyd1124 Also, NPC/Enemy AI.
I'll try to take a look at other LU server emulators and do some work on WLUS. I think it's a great concept.

**Comment by ghost** [comment]
AI is by far the hardest thing. No other publicly available emulator has it implemented. You should probably look at the LU docs before you try anything because if you aren’t familiar with how these systems work you’re not going to get very far https://lu-docs.readthedocs.io/en/latest/

**Comment by moliata** [comment]
Yup, I did read through the documentation a couple of weeks ago. I am not going to work on AI or mini-games (at least any time soon). Given the fact that I don't have a lot of time myself and am working on different projects, I'll try to work on support for missions
